# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: regularity
version: '0.0.0'
github: "mgree/regularity"
license: MIT
author: "Michael Greenberg"
maintainer: "Michael Greenberg"
synopsis: Regular, degular, shmegular languages.
description: regularity is a toolkit for working with regular languages, computing various operations on them.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  regularity:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - regularity
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  regularity-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - regularity
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  regularity-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - regularity
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
